### ISSUE TITLE
Start using releases to make it easier to config. 

### ISSUE THREAD

**Issue by jtmiclat** [thinkingmachines/coding-style#10]
```yaml
repos:
- repo: https://github.com/thinkingmachines/coding-style
  rev: master
```
The above example works but might break if users installed to 2 different versions of hooks are applied. An example that happened is we were using 2 different versions of `prettier-standard` causing 2 different ways to validate if the commit has passed. 

The solution is to use git commit when handling revs. for example

```yaml
repos:
- repo: https://github.com/thinkingmachines/coding-style
    rev: 1e8d7a7ee1af18b5c10b6acf4e7d01cf4774ea4e
```
This guarantees reproducibility but is ugly and hard to keep track of the meaning of each rev. What would be nice if we have releases to make it easier. I suggest we use Calendar Versioning of the format `YYYY.MM.DD`
https://calver.org/. SemVer is useful when managing dependencies but since this is a tool there shouldn't be backward compatibility to worry about and the version itself all the information of when the release was made. 

```yaml
repos:
- repo: https://github.com/thinkingmachines/coding-style
    rev: 2020.03.23
```
