### ISSUE TITLE
Add hooks from pre-commit/pre-commit-hooks as sanity checks

### ISSUE THREAD

**Issue by inpaner** [thinkingmachines/coding-style#32]
We can add existing hooks from [pre-commit](https://github.com/pre-commit/pre-commit-hooks) to make projects more consistently clean. The hooks below are what I generally use but more hooks can be found in the repo.

`.pre-commit-config.yaml`
```
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-yaml
 ```
